### ISSUE TITLE
logs files

### ISSUE THREAD

**Issue by OlgaVT** [AlgoLab/galig#13]
Hi,

I am trying to run ASGAL and I am interested: how the files in the logs/ASGAL folder are produced and what do they mean? In the genomewide mode are they produced for each gene in the genome annotation or only for some of them? Which ones?

Thank you!

**Comment by ldenti** [comment]
Hi,
the files in `logs/ASGAL` contain what ASGAL outputs to stderr (if everything worked, all those files should be empty, otherwise they should contain information on what went wrong).

In that folder you can find a file for each gene that is processed by asgal: if we think we have at least one read on a gene, than you will find a file for that gene. In genomewide mode, salmon is used to perform transcript quantification and then the reads used to quantify the transcripts of a gene are "assigned" to that gene and mapped to its splicing graph.

I hope this may help you. Let me know if you have other questions.

**Comment by OlgaVT** [comment]
Thank you!
